version: '3.1'
volumes:
  bundle:
    driver: local
services:
  rails:
    build: .
    volumes:
    - .:/workspace
    - bundle:/usr/local/bundle
    ports:
    - '19654:3000'
    working_dir: /workspace
    command: sh

